name: OIDC Test AWS

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  oidc-test:
    name: Test GitHub OIDC to AWS
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Configure AWS credentials from GitHub OIDC
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ vars.AWS_GITHUB_APP_ROLE_ARN }}
          aws-region: eu-west-3
          role-session-name: github-oidc-test
      - name: Verify AWS Identity
        run: aws sts get-caller-identity
